<?php

/**
 * Implementation of hook_menu().
 */
function apachesolr_views_integration_menu() {
  $items = array();
  $items['solrsearch'] = array(
    'title' => 'Search',
    'description' => 'Search the site with Apache Solr.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apachesolr_views_integration_form'),
    'access callback' => 'user_access',
    'access arguments' => array(),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Returns the search form.
 */
function apachesolr_views_integration_form() {
  $form = array();
  $form['query'] = array(
    '#prefix' => '<p>',
    '#type' => 'textfield',
    '#title' => t('Enter your keywords'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#suffix' => '</p>',
  );
  return $form;
}

/*
 * Ensures that somethig is entered into the search field.
 */
function apachesolr_views_integration_form_validate($form, &$form_state) {
  if ($form_state['values']['query'] == '') {
    form_set_error('query', t('Please enter some keywords.'));
  }
}

/*
 * Redirects to the search results.
 */
function apachesolr_views_integration_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'solrsearch/results/' . urlencode($form_state['values']['query']);
}

