<?php

// $Id: apachesolr_views.module,v 1.1 2008/08/28 11:05:48 drunkenmonkey Exp $

/**
 * Implementation of hook_menu().
 */
function apachesolr_views_menu() {
  $items = array();
  $items['solrsearch'] = array(
    'title' => 'Search',
    'description' => 'Search the site with Apache Solr.',
    'page callback' => 'apachesolr_views_search_page',
    'page arguments' => array(),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Shows the search form or results, depending on arguments.
 */
function apachesolr_views_search_page() {
  $args = func_get_args();
  if (count($args) > 0) {
    $arg = array_shift($args);
    $output = views_embed_view('apachesolr_search', 'default', $arg);
    $response = apachesolr_static_response_cache();
    if ($response->numFound == 0) {
      $output = '<p>' . t('Your search yielded no results.') . '</p>';
    }
    return drupal_get_form('apachesolr_views_form', $arg) . $output;
  }
  else {
    return drupal_get_form('apachesolr_views_form');
  }
}

/**
 * Returns the search form.
 */
function apachesolr_views_form(&$form_state = array(), $keys = '') {
  $form = array();
  $form['keys'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter your keywords'),
    '#maxlength' => 255,
    '#default_value' => $keys,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  return $form;
}

/*
 * Ensures that somethig is entered into the search field.
 */
function apachesolr_views_form_validate($form, &$form_state) {
  if ($form_state['values']['keys'] == '') {
    form_set_error('keys', t('Please enter some keywords.'));
  }
}

/*
 * Redirects to the search results.
 */
function apachesolr_views_form_submit($form, &$form_state) {
  $form_state['redirect'] = 'solrsearch/' . /*urlencode(str_replace('+', ' ', */$form_state['values']['keys'];
}

