<?php
// $Id: apachesolr_og.module,v 1.10 2010/05/17 00:32:26 pwolanin Exp $

/**
 * @file
 *   Integrates Organic Group info with Apache Solr search application.
 */

/**
 * Implements hook_menu().
 */
function apachesolr_og_menu() {
  return array(
    'admin/og/apachesolr_og' => array(
      'title'            => 'Apache Solr OG configuration ',
      'description'      => 'Apache Solr OG facet settings for group posts.',
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('apachesolr_og_admin'),
      'access arguments' => array('administer search'),
    ),
  );
}

/**
 * Build a settings form.
 */
function apachesolr_og_admin() {
  $form = array();
  $form['apachesolr_og_groupnode'] = array(
    '#type' => 'radios',
    '#title' => t('Is the group node "included" within a group along with that group\'s posts'),
    '#description' => t('Should group nodes be indexed as belonging to their own group for the purposes of faceting?'),
    '#options' => array(0 => t('Not included'), 1 => t('Included')),
    '#default_value' => variable_get('apachesolr_og_groupnode', 0),
  );
  $form = system_settings_form($form);
  $form['#submit'][] = 'apachesolr_og_reindex';
  return $form;
}

/**
 * Submit function to make group nodes as needing re-indexing.
 */
function apachesolr_og_reindex() {
  $result = db_query("SELECT nid FROM {og}");
  foreach ($result as $og){
    apachesolr_mark_node($og->nid);
  }
  drupal_set_message(t('All group nodes marked for re-indexing'));
}

/**
 * Implements hook_apachesolr_update_index().
 */
function apachesolr_og_apachesolr_update_index(&$document, $node) {
  // Index group posts
  if (!empty($node->og_groups)) {
    foreach ($node->og_groups as $gid) {
      $document->setMultiValue(apachesolr_og_gid_key(), $gid);
    }
  }
  elseif (isset($node->og_description) && variable_get('apachesolr_og_groupnode', 0)) {
    // Index the group node itself as in the group.
    $document->setMultiValue(apachesolr_og_gid_key(), $node->nid);
  }
}

/**
 * Implements hook_apachesolr_modify_query().
 */
function apachesolr_og_apachesolr_modify_query(&$query, &$params, $caller) {
  // Fetch the group ID in results - however, this is currently not used.
  // May be useful for custom theming.
  if ($caller == 'apachesolr_search') {
    $params['fl'] .= ',' . apachesolr_og_gid_key();
  }
}

/**
 * Implements hook_apachesolr_process_results().
 */
function apachesolr_og_apachesolr_process_results(&$results) {
  $key = apachesolr_og_gid_key();
  $groups = array();
  foreach ($results as $idx => $r) {
    if (!is_array($r['node']->$key)) {
      $results[$idx]['node']->$key = $r['node']->$key ? array($r['node']->$key) : array();
    }
    foreach ($results[$idx]['node']->$key as $gid) {
      $groups[$gid] = $gid;
    }
  }

  if ($groups) {
    // Copied code from og_node_groups_distinguish() and og_nodeapi().
    $accessible_groups = array();
    $query = db_select('node', 'n')
      ->fields('n', array('nid'))  
      ->condition('n.nid', $groups, 'IN');
    $query->addTag('node_access');
    $result = $query->execute();
    foreach ($result as $row){
      $accessible_groups[] = $row->nid;
    }
    foreach ($results as $idx => $r) {
      $accessible = array_intersect($results[$idx]['node']->$key, $accessible_groups);
      if ($accessible) {
        $results[$idx]['extra'][] = format_plural(count($accessible), '1 group', '@count groups');
      }
    }
  }
}

/**
 * Apachesolr index name for Organic group id
 */
function apachesolr_og_gid_key() {
  $group_id = array(
    'name'       => 'og_gid',
    'multiple'   => TRUE,
    'index_type' => 'integer',
  );
  // Returns im_og_gid.
  return apachesolr_index_key($group_id);
}

/**
 * Implements hook_apachesolr_facets().
 */
function apachesolr_og_apachesolr_facets() {
  $key = apachesolr_og_gid_key();
  $facets[$key] = array(
    'info' => t('Apache Solr OG: Filter by Organic Group'),
    'facet_field' => $key,
  );
  return $facets;
}

/**
 * Implements hook_block().
 */
function apachesolr_og_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $enabled_facets = apachesolr_get_enabled_facets('apachesolr_og');
      $facets = apachesolr_og_apachesolr_facets();
      // Add the blocks
      $blocks = array();
      foreach ($enabled_facets as $delta => $facet_field) {
        if (isset($facets[$delta])) {
          $blocks[$delta] = $facets[$delta] + array('cache' => DRUPAL_CACHE_PER_PAGE);
        }
      }
      return $blocks;

    case 'view':
      if (apachesolr_has_searched()) {
        if ($delta != apachesolr_og_gid_key()) {
          return;
        }

        $response = apachesolr_static_response_cache();
        if (empty($response)) {
          return;
        }
        $query = apachesolr_current_query();

        return apachesolr_facet_block($response, $query, 'apachesolr_og', $delta, $delta, t('Filter by Group'), 'apachesolr_og_group_name');
      }
      break;

    case 'configure':
      return apachesolr_facetcount_form('apachesolr_og', $delta);
    case 'save':
      apachesolr_facetcount_save($edit);
      break;
  }
}

/**
 * Callback function for the 'Filter by group' facet block.
 */
function apachesolr_og_group_name($facet, &$options) {
  if (!is_numeric($facet)) {
    $options['html'] = TRUE;
    //TODO: theme_placeholder no longer exists in D7
    return theme('placeholder', t('No group'));
  }

  return db_query("SELECT title FROM {node} WHERE nid = :nid", array(':nid' => $facet))->fetchField();
}

/**
 * Implements hook_theme().
 *
 * The breadcrumb function assumes that apachesolr_og_gid_key() returns im_og_gid
 * If that changes, modify the theme name appropriately
 */
function apachesolr_og_theme() {
  return array(
    'apachesolr_breadcrumb_im_og_gid' => array('arguments' => array('group_id' => NULL)),
  );
}

/**
 * Theme the breadcrumb.
 */
function theme_apachesolr_breadcrumb_im_og_gid($field) {
  $group_id = $field['#value'];
  if (!is_numeric($group_id)) {
    return t('No group');
  }

  return db_query("SELECT title FROM {node} WHERE nid = :nid", array(':nid' => $group_id))->fetchField();
}

